### ISSUE TITLE
/collections

### ISSUE THREAD

**Issue by michael-wynne-wsu** [MukurtuCMS/Mukurtu-CMS#104]
- [x] Only display top-level/parent collections.
- [x] Remove search box.
- [x] Create a new issue for revisiting search (Michael). #653 
- [x] Create a new issue for manually ordering collections (Michael). #654
- [x] Ensure that options in the sort drop down represent accurate choices (basically just remove search relevance).
- [x] Use alternate colour for background box (bone).
- [x] Update all other colours etc as needed for accessibility.
- [x] Teaser should include title, item count (includes child collections), summary, and image. No strong opinion on other style elements at this time.
- [x] Pick and set an image ratio - scale and crop.
- ~~[ ] Image should link to collection pages. Nope, this is an accessibility issue.~~
- [x] Create a new issue for auto-selecting an image if one is not manually assigned (Michael). #187 

Screenshot below shows a field complete v3 preview/teaser.

![Image](https://github.com/user-attachments/assets/6386b095-5aa8-44cb-b175-e70b3140da18)

-----
/collections should only display top-level collections. Currently displaying all collections.

I don't think this needs to be user configurable, I can't think of a relevant use case for display sub-collections on the main collections browse page.

**Comment by steve-taylor-wsu** [comment]
If we don't show subcollections on this page, a user will not be able to search for subcollections. Is this okay? The plan was to push subcollections down with relevance manipulation, similar to what we do with multipage items on browse. I have no horse in this race, just stating our thinking from before.

**Comment by michael-wynne-wsu** [comment]
Ooh shoot I had forgotten that.

Okay, leave as is. Not ideal, but I think that discoverability will be useful. Maybe we can find some way to flag/indicate that a sub-collection is part of X collection or something...

**Comment by steve-taylor-wsu** [comment]
Let's leave this issue open. We can take another pass and see if there's a better solution. We could also consider two separate pages, one for "searching" and one as more of an entry point into truly browsing the collections (more "presentation" oriented).

**Comment by michael-wynne-wsu** [comment]
Thanks Steve - if another pass turns anything up that would be nice.

That said, I agree that offering two pages would be a viable way to go if not. That lets admins either pick what they prefer, or they can expose both to users.

**Comment by michael-wynne-wsu** [comment]
Would like something more space efficient. 

Search/sort is NOT that useful

**Comment by pjudge** [comment]
Handoff note: I sadly didn't get to this :(

**Comment by michael-wynne-wsu** [comment]
Partially themed. Can refer to v3 for the basics.

- [ ] Remove "add collection" button.
- [ ] Improve search tool.
- [ ] Collection title needs to be a different colour.
- [ ] Summary needs to be displayed.
- [ ] Featured image needs to be resized.
- [ ] What displays if not image?

![Screenshot 2024-06-11 at 12 00 37 PM](https://github.com/MukurtuCMS/Mukurtu-CMS/assets/88502274/ae8f5eeb-cfe3-454c-947d-6261e1bcd031)

![Screenshot 2024-06-11 at 12 01 05 PM](https://github.com/MukurtuCMS/Mukurtu-CMS/assets/88502274/41fff97b-13f2-43a7-8247-5bd669de220e)

**Comment by michael-wynne-wsu** [comment]
- omit search box

**Comment by michael-wynne-wsu** [comment]
@pjudge I updated the initial post here with all the details we discussed (I think)

**Comment by michael-wynne-wsu** [comment]
Final notes @pjudge 
- [ ] Only display parent/top level collections
- [ ] Confirm if two links to content does/does not fail accessibility tests

**Comment by michael-wynne-wsu** [comment]
Thank you so much @pjudge ! I've moved everything outstanding to dedicated tickets (mostly linked here), and am closing this.
