### ISSUE TITLE
Field complete tracking

### ISSUE THREAD

**Issue by michael-wynne-wsu** [MukurtuCMS/Mukurtu-CMS#546]
Are all of our entities, content, etc field complete?

- [ ] Communities
- [ ] Cultural protocols
- [ ] Categories
- [ ] Taxonomies
- [ ] Digital heritage items
- [ ] Collections
- [ ] Personal collections
- [ ] Community records
- [ ] Multi-page items
- [ ] Dictionary words (includes word entries)
- [ ] Word lists
- [ ] Person records
- [ ] Media adidia
